// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SF.SGL.Infra.Data.Contextos;

namespace SF.SGL.Infra.Data.Migrations
{
    [DbContext(typeof(SGLContexto))]
    [Migration("20211007152146_ParametroExpurgo")]
    partial class ParametroExpurgo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SF.SGL.Dominio.Entidades.EntidadeParametroExpurgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_parametro_expurgo_log")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntidadeSistemaId")
                        .HasColumnType("int")
                        .HasColumnName("cd_sistema");

                    b.Property<int>("ParametroExpurgoLogAuditoria")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasColumnName("pr_expurgo_log_auditoria");

                    b.Property<int>("ParametroExpurgoLogOperacao")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasColumnName("pr_expurgo_log_operacao");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeSistemaId");

                    b.ToTable("parametro_expurgo_log");
                });

            modelBuilder.Entity("SF.SGL.Dominio.Entidades.EntidadeSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_sistema")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nm_sistema");

                    b.Property<string>("UrlServicoConsultaLog")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nm_url_servico_consulta_log");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nm_usuario_servico_consulta_log");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nm_senha_servico_consulta_log");

                    b.HasKey("Id");

                    b.ToTable("sistema");
                });

            modelBuilder.Entity("SF.SGL.Dominio.Entidades.EntidadeParametroExpurgo", b =>
                {
                    b.HasOne("SF.SGL.Dominio.Entidades.EntidadeSistema", "EntidadeSistema")
                        .WithMany()
                        .HasForeignKey("EntidadeSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadeSistema");
                });
#pragma warning restore 612, 618
        }
    }
}
