//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_SGL_WFC.ServiceReference
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ParametroPaginacaoLogDTO", Namespace = "http://schemas.datacontract.org/2004/07/SF.SGL.DTO.Externo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SF_SGL_WFC.ServiceReference.ParametroConsultaLogOperacaoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SF_SGL_WFC.ServiceReference.ParametroConsultaLogAuditoriaDTO))]
    public partial class ParametroPaginacaoLogDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampoOrdenacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DirecaoOrdenacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaginaAtualField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeRegistroPaginaField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampoOrdenacao
        {
            get
            {
                return this.CampoOrdenacaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CampoOrdenacaoField, value) != true))
                {
                    this.CampoOrdenacaoField = value;
                    this.RaisePropertyChanged("CampoOrdenacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DirecaoOrdenacao
        {
            get
            {
                return this.DirecaoOrdenacaoField;
            }
            set
            {
                if ((this.DirecaoOrdenacaoField.Equals(value) != true))
                {
                    this.DirecaoOrdenacaoField = value;
                    this.RaisePropertyChanged("DirecaoOrdenacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaginaAtual
        {
            get
            {
                return this.PaginaAtualField;
            }
            set
            {
                if ((this.PaginaAtualField.Equals(value) != true))
                {
                    this.PaginaAtualField = value;
                    this.RaisePropertyChanged("PaginaAtual");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantidadeRegistroPagina
        {
            get
            {
                return this.QuantidadeRegistroPaginaField;
            }
            set
            {
                if ((this.QuantidadeRegistroPaginaField.Equals(value) != true))
                {
                    this.QuantidadeRegistroPaginaField = value;
                    this.RaisePropertyChanged("QuantidadeRegistroPagina");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ParametroConsultaLogOperacaoDTO", Namespace = "http://schemas.datacontract.org/2004/07/SF.SGL.DTO.Externo")]
    [System.SerializableAttribute()]
    public partial class ParametroConsultaLogOperacaoDTO : SF_SGL_WFC.ServiceReference.ParametroPaginacaoLogDTO
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIdentificadorUsuarioField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoLogOperacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExcecaoCapturadaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionalidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> HorarioFinalField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> HorarioInicialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemErroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PeriodoFinalField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PeriodoInicialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SubTipoRegistroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoRegistroField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificadorUsuario
        {
            get
            {
                return this.CodigoIdentificadorUsuarioField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodigoIdentificadorUsuarioField, value) != true))
                {
                    this.CodigoIdentificadorUsuarioField = value;
                    this.RaisePropertyChanged("CodigoIdentificadorUsuario");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoLogOperacao
        {
            get
            {
                return this.CodigoLogOperacaoField;
            }
            set
            {
                if ((this.CodigoLogOperacaoField.Equals(value) != true))
                {
                    this.CodigoLogOperacaoField = value;
                    this.RaisePropertyChanged("CodigoLogOperacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExcecaoCapturada
        {
            get
            {
                return this.ExcecaoCapturadaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExcecaoCapturadaField, value) != true))
                {
                    this.ExcecaoCapturadaField = value;
                    this.RaisePropertyChanged("ExcecaoCapturada");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funcionalidade
        {
            get
            {
                return this.FuncionalidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FuncionalidadeField, value) != true))
                {
                    this.FuncionalidadeField = value;
                    this.RaisePropertyChanged("Funcionalidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> HorarioFinal
        {
            get
            {
                return this.HorarioFinalField;
            }
            set
            {
                if ((this.HorarioFinalField.Equals(value) != true))
                {
                    this.HorarioFinalField = value;
                    this.RaisePropertyChanged("HorarioFinal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> HorarioInicial
        {
            get
            {
                return this.HorarioInicialField;
            }
            set
            {
                if ((this.HorarioInicialField.Equals(value) != true))
                {
                    this.HorarioInicialField = value;
                    this.RaisePropertyChanged("HorarioInicial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemErro
        {
            get
            {
                return this.MensagemErroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MensagemErroField, value) != true))
                {
                    this.MensagemErroField = value;
                    this.RaisePropertyChanged("MensagemErro");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PeriodoFinal
        {
            get
            {
                return this.PeriodoFinalField;
            }
            set
            {
                if ((this.PeriodoFinalField.Equals(value) != true))
                {
                    this.PeriodoFinalField = value;
                    this.RaisePropertyChanged("PeriodoFinal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PeriodoInicial
        {
            get
            {
                return this.PeriodoInicialField;
            }
            set
            {
                if ((this.PeriodoInicialField.Equals(value) != true))
                {
                    this.PeriodoInicialField = value;
                    this.RaisePropertyChanged("PeriodoInicial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SubTipoRegistro
        {
            get
            {
                return this.SubTipoRegistroField;
            }
            set
            {
                if ((this.SubTipoRegistroField.Equals(value) != true))
                {
                    this.SubTipoRegistroField = value;
                    this.RaisePropertyChanged("SubTipoRegistro");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoRegistro
        {
            get
            {
                return this.TipoRegistroField;
            }
            set
            {
                if ((this.TipoRegistroField.Equals(value) != true))
                {
                    this.TipoRegistroField = value;
                    this.RaisePropertyChanged("TipoRegistro");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ParametroConsultaLogAuditoriaDTO", Namespace = "http://schemas.datacontract.org/2004/07/SF.SGL.DTO.Externo")]
    [System.SerializableAttribute()]
    public partial class ParametroConsultaLogAuditoriaDTO : SF_SGL_WFC.ServiceReference.ParametroPaginacaoLogDTO
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIdentificadorUsuarioField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoLogAuditoriaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionalidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> HorarioFinalField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> HorarioInicialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PeriodoFinalField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PeriodoInicialField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificadorUsuario
        {
            get
            {
                return this.CodigoIdentificadorUsuarioField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodigoIdentificadorUsuarioField, value) != true))
                {
                    this.CodigoIdentificadorUsuarioField = value;
                    this.RaisePropertyChanged("CodigoIdentificadorUsuario");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoLogAuditoria
        {
            get
            {
                return this.CodigoLogAuditoriaField;
            }
            set
            {
                if ((this.CodigoLogAuditoriaField.Equals(value) != true))
                {
                    this.CodigoLogAuditoriaField = value;
                    this.RaisePropertyChanged("CodigoLogAuditoria");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funcionalidade
        {
            get
            {
                return this.FuncionalidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FuncionalidadeField, value) != true))
                {
                    this.FuncionalidadeField = value;
                    this.RaisePropertyChanged("Funcionalidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> HorarioFinal
        {
            get
            {
                return this.HorarioFinalField;
            }
            set
            {
                if ((this.HorarioFinalField.Equals(value) != true))
                {
                    this.HorarioFinalField = value;
                    this.RaisePropertyChanged("HorarioFinal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> HorarioInicial
        {
            get
            {
                return this.HorarioInicialField;
            }
            set
            {
                if ((this.HorarioInicialField.Equals(value) != true))
                {
                    this.HorarioInicialField = value;
                    this.RaisePropertyChanged("HorarioInicial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operacao
        {
            get
            {
                return this.OperacaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OperacaoField, value) != true))
                {
                    this.OperacaoField = value;
                    this.RaisePropertyChanged("Operacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PeriodoFinal
        {
            get
            {
                return this.PeriodoFinalField;
            }
            set
            {
                if ((this.PeriodoFinalField.Equals(value) != true))
                {
                    this.PeriodoFinalField = value;
                    this.RaisePropertyChanged("PeriodoFinal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PeriodoInicial
        {
            get
            {
                return this.PeriodoInicialField;
            }
            set
            {
                if ((this.PeriodoInicialField.Equals(value) != true))
                {
                    this.PeriodoInicialField = value;
                    this.RaisePropertyChanged("PeriodoInicial");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RepostaConsultaLogAuditoriaDTO", Namespace = "http://schemas.datacontract.org/2004/07/SF.SGL.DTO.Externo")]
    [System.SerializableAttribute()]
    public partial class RepostaConsultaLogAuditoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRetornoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SF_SGL_WFC.ServiceReference.LogAuditoriaDTO[] LogAuditoriaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemRetornoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeTotalRegistrosEncontradosField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRetorno
        {
            get
            {
                return this.CodigoRetornoField;
            }
            set
            {
                if ((this.CodigoRetornoField.Equals(value) != true))
                {
                    this.CodigoRetornoField = value;
                    this.RaisePropertyChanged("CodigoRetorno");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SF_SGL_WFC.ServiceReference.LogAuditoriaDTO[] LogAuditoria
        {
            get
            {
                return this.LogAuditoriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LogAuditoriaField, value) != true))
                {
                    this.LogAuditoriaField = value;
                    this.RaisePropertyChanged("LogAuditoria");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemRetorno
        {
            get
            {
                return this.MensagemRetornoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MensagemRetornoField, value) != true))
                {
                    this.MensagemRetornoField = value;
                    this.RaisePropertyChanged("MensagemRetorno");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantidadeTotalRegistrosEncontrados
        {
            get
            {
                return this.QuantidadeTotalRegistrosEncontradosField;
            }
            set
            {
                if ((this.QuantidadeTotalRegistrosEncontradosField.Equals(value) != true))
                {
                    this.QuantidadeTotalRegistrosEncontradosField = value;
                    this.RaisePropertyChanged("QuantidadeTotalRegistrosEncontrados");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LogAuditoriaDTO", Namespace = "http://schemas.datacontract.org/2004/07/SF.SGL.DTO.Externo")]
    [System.SerializableAttribute()]
    public partial class LogAuditoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIdentificadorCertificadoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIdentificadorUsuarioField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoLogAuditoriaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConteudoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataOcorrenciaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoIpField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HoraOcorrenciaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeFuncionalidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeOperacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeUsuarioField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificadorCertificado
        {
            get
            {
                return this.CodigoIdentificadorCertificadoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodigoIdentificadorCertificadoField, value) != true))
                {
                    this.CodigoIdentificadorCertificadoField = value;
                    this.RaisePropertyChanged("CodigoIdentificadorCertificado");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificadorUsuario
        {
            get
            {
                return this.CodigoIdentificadorUsuarioField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodigoIdentificadorUsuarioField, value) != true))
                {
                    this.CodigoIdentificadorUsuarioField = value;
                    this.RaisePropertyChanged("CodigoIdentificadorUsuario");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoLogAuditoria
        {
            get
            {
                return this.CodigoLogAuditoriaField;
            }
            set
            {
                if ((this.CodigoLogAuditoriaField.Equals(value) != true))
                {
                    this.CodigoLogAuditoriaField = value;
                    this.RaisePropertyChanged("CodigoLogAuditoria");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conteudo
        {
            get
            {
                return this.ConteudoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ConteudoField, value) != true))
                {
                    this.ConteudoField = value;
                    this.RaisePropertyChanged("Conteudo");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataOcorrencia
        {
            get
            {
                return this.DataOcorrenciaField;
            }
            set
            {
                if ((this.DataOcorrenciaField.Equals(value) != true))
                {
                    this.DataOcorrenciaField = value;
                    this.RaisePropertyChanged("DataOcorrencia");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoIp
        {
            get
            {
                return this.EnderecoIpField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EnderecoIpField, value) != true))
                {
                    this.EnderecoIpField = value;
                    this.RaisePropertyChanged("EnderecoIp");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HoraOcorrencia
        {
            get
            {
                return this.HoraOcorrenciaField;
            }
            set
            {
                if ((this.HoraOcorrenciaField.Equals(value) != true))
                {
                    this.HoraOcorrenciaField = value;
                    this.RaisePropertyChanged("HoraOcorrencia");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFuncionalidade
        {
            get
            {
                return this.NomeFuncionalidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeFuncionalidadeField, value) != true))
                {
                    this.NomeFuncionalidadeField = value;
                    this.RaisePropertyChanged("NomeFuncionalidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeOperacao
        {
            get
            {
                return this.NomeOperacaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeOperacaoField, value) != true))
                {
                    this.NomeOperacaoField = value;
                    this.RaisePropertyChanged("NomeOperacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuario
        {
            get
            {
                return this.NomeUsuarioField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeUsuarioField, value) != true))
                {
                    this.NomeUsuarioField = value;
                    this.RaisePropertyChanged("NomeUsuario");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RepostaConsultaLogOperacaoDTO", Namespace = "http://schemas.datacontract.org/2004/07/SF.SGL.DTO.Externo")]
    [System.SerializableAttribute()]
    public partial class RepostaConsultaLogOperacaoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoRetornoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SF_SGL_WFC.ServiceReference.LogOperacaoDTO[] LogOperacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemRetornoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeTotalRegistrosEncontradosField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRetorno
        {
            get
            {
                return this.CodigoRetornoField;
            }
            set
            {
                if ((this.CodigoRetornoField.Equals(value) != true))
                {
                    this.CodigoRetornoField = value;
                    this.RaisePropertyChanged("CodigoRetorno");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SF_SGL_WFC.ServiceReference.LogOperacaoDTO[] LogOperacao
        {
            get
            {
                return this.LogOperacaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LogOperacaoField, value) != true))
                {
                    this.LogOperacaoField = value;
                    this.RaisePropertyChanged("LogOperacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemRetorno
        {
            get
            {
                return this.MensagemRetornoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MensagemRetornoField, value) != true))
                {
                    this.MensagemRetornoField = value;
                    this.RaisePropertyChanged("MensagemRetorno");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantidadeTotalRegistrosEncontrados
        {
            get
            {
                return this.QuantidadeTotalRegistrosEncontradosField;
            }
            set
            {
                if ((this.QuantidadeTotalRegistrosEncontradosField.Equals(value) != true))
                {
                    this.QuantidadeTotalRegistrosEncontradosField = value;
                    this.RaisePropertyChanged("QuantidadeTotalRegistrosEncontrados");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LogOperacaoDTO", Namespace = "http://schemas.datacontract.org/2004/07/SF.SGL.DTO.Externo")]
    [System.SerializableAttribute()]
    public partial class LogOperacaoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIdentificadorCertificadoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIdentificadorUsuarioField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoLogOperacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataOcorrenciaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalhesDaExcecaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoIpField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExcecaoCapturadaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HoraOcorrenciaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemErroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeFuncionalidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeUsuarioField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubTipoRegistroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoRegistroField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificadorCertificado
        {
            get
            {
                return this.CodigoIdentificadorCertificadoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodigoIdentificadorCertificadoField, value) != true))
                {
                    this.CodigoIdentificadorCertificadoField = value;
                    this.RaisePropertyChanged("CodigoIdentificadorCertificado");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificadorUsuario
        {
            get
            {
                return this.CodigoIdentificadorUsuarioField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodigoIdentificadorUsuarioField, value) != true))
                {
                    this.CodigoIdentificadorUsuarioField = value;
                    this.RaisePropertyChanged("CodigoIdentificadorUsuario");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoLogOperacao
        {
            get
            {
                return this.CodigoLogOperacaoField;
            }
            set
            {
                if ((this.CodigoLogOperacaoField.Equals(value) != true))
                {
                    this.CodigoLogOperacaoField = value;
                    this.RaisePropertyChanged("CodigoLogOperacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataOcorrencia
        {
            get
            {
                return this.DataOcorrenciaField;
            }
            set
            {
                if ((this.DataOcorrenciaField.Equals(value) != true))
                {
                    this.DataOcorrenciaField = value;
                    this.RaisePropertyChanged("DataOcorrencia");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalhesDaExcecao
        {
            get
            {
                return this.DetalhesDaExcecaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DetalhesDaExcecaoField, value) != true))
                {
                    this.DetalhesDaExcecaoField = value;
                    this.RaisePropertyChanged("DetalhesDaExcecao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoIp
        {
            get
            {
                return this.EnderecoIpField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EnderecoIpField, value) != true))
                {
                    this.EnderecoIpField = value;
                    this.RaisePropertyChanged("EnderecoIp");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExcecaoCapturada
        {
            get
            {
                return this.ExcecaoCapturadaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExcecaoCapturadaField, value) != true))
                {
                    this.ExcecaoCapturadaField = value;
                    this.RaisePropertyChanged("ExcecaoCapturada");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HoraOcorrencia
        {
            get
            {
                return this.HoraOcorrenciaField;
            }
            set
            {
                if ((this.HoraOcorrenciaField.Equals(value) != true))
                {
                    this.HoraOcorrenciaField = value;
                    this.RaisePropertyChanged("HoraOcorrencia");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemErro
        {
            get
            {
                return this.MensagemErroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MensagemErroField, value) != true))
                {
                    this.MensagemErroField = value;
                    this.RaisePropertyChanged("MensagemErro");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFuncionalidade
        {
            get
            {
                return this.NomeFuncionalidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeFuncionalidadeField, value) != true))
                {
                    this.NomeFuncionalidadeField = value;
                    this.RaisePropertyChanged("NomeFuncionalidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuario
        {
            get
            {
                return this.NomeUsuarioField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeUsuarioField, value) != true))
                {
                    this.NomeUsuarioField = value;
                    this.RaisePropertyChanged("NomeUsuario");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubTipoRegistro
        {
            get
            {
                return this.SubTipoRegistroField;
            }
            set
            {
                if ((this.SubTipoRegistroField.Equals(value) != true))
                {
                    this.SubTipoRegistroField = value;
                    this.RaisePropertyChanged("SubTipoRegistro");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoRegistro
        {
            get
            {
                return this.TipoRegistroField;
            }
            set
            {
                if ((this.TipoRegistroField.Equals(value) != true))
                {
                    this.TipoRegistroField = value;
                    this.RaisePropertyChanged("TipoRegistro");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference.IServicoLog")]
    public interface IServicoLog
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicoLog/ConsultarLogAuditoria", ReplyAction = "http://tempuri.org/IServicoLog/ConsultarLogAuditoriaResponse")]
        SF_SGL_WFC.ServiceReference.RepostaConsultaLogAuditoriaDTO ConsultarLogAuditoria(SF_SGL_WFC.ServiceReference.ParametroConsultaLogAuditoriaDTO parametroConsulta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicoLog/ConsultarLogAuditoria", ReplyAction = "http://tempuri.org/IServicoLog/ConsultarLogAuditoriaResponse")]
        System.Threading.Tasks.Task<SF_SGL_WFC.ServiceReference.RepostaConsultaLogAuditoriaDTO> ConsultarLogAuditoriaAsync(SF_SGL_WFC.ServiceReference.ParametroConsultaLogAuditoriaDTO parametroConsulta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicoLog/ConsultarLogOperacao", ReplyAction = "http://tempuri.org/IServicoLog/ConsultarLogOperacaoResponse")]
        SF_SGL_WFC.ServiceReference.RepostaConsultaLogOperacaoDTO ConsultarLogOperacao(SF_SGL_WFC.ServiceReference.ParametroConsultaLogOperacaoDTO parametroConsulta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicoLog/ConsultarLogOperacao", ReplyAction = "http://tempuri.org/IServicoLog/ConsultarLogOperacaoResponse")]
        System.Threading.Tasks.Task<SF_SGL_WFC.ServiceReference.RepostaConsultaLogOperacaoDTO> ConsultarLogOperacaoAsync(SF_SGL_WFC.ServiceReference.ParametroConsultaLogOperacaoDTO parametroConsulta);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoLogChannel : SF_SGL_WFC.ServiceReference.IServicoLog, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoLogClient : System.ServiceModel.ClientBase<SF_SGL_WFC.ServiceReference.IServicoLog>, SF_SGL_WFC.ServiceReference.IServicoLog
    {

        public ServicoLogClient()
        {
        }

        public ServicoLogClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServicoLogClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicoLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicoLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public SF_SGL_WFC.ServiceReference.RepostaConsultaLogAuditoriaDTO ConsultarLogAuditoria(SF_SGL_WFC.ServiceReference.ParametroConsultaLogAuditoriaDTO parametroConsulta)
        {
            return base.Channel.ConsultarLogAuditoria(parametroConsulta);
        }

        public System.Threading.Tasks.Task<SF_SGL_WFC.ServiceReference.RepostaConsultaLogAuditoriaDTO> ConsultarLogAuditoriaAsync(SF_SGL_WFC.ServiceReference.ParametroConsultaLogAuditoriaDTO parametroConsulta)
        {
            return base.Channel.ConsultarLogAuditoriaAsync(parametroConsulta);
        }

        public SF_SGL_WFC.ServiceReference.RepostaConsultaLogOperacaoDTO ConsultarLogOperacao(SF_SGL_WFC.ServiceReference.ParametroConsultaLogOperacaoDTO parametroConsulta)
        {
            return base.Channel.ConsultarLogOperacao(parametroConsulta);
        }

        public System.Threading.Tasks.Task<SF_SGL_WFC.ServiceReference.RepostaConsultaLogOperacaoDTO> ConsultarLogOperacaoAsync(SF_SGL_WFC.ServiceReference.ParametroConsultaLogOperacaoDTO parametroConsulta)
        {
            return base.Channel.ConsultarLogOperacaoAsync(parametroConsulta);
        }
    }
}
